In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv(r"D:\Sasi\GUVI HCL AI-ML\EV_Charging Project\data\raw\ChargingRecords.csv")
display(df.head())
display(df.shape)
df.info()

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
0,0,1,1,hotel,0,15-09-2022,20:54:02,15-09-2022,23:59:13,15-09-2022 20:54,15-09-2022 23:59,185,20.36
1,0,1,1,hotel,0,14-09-2022,20:01:05,14-09-2022,21:31:04,14-09-2022 20:01,14-09-2022 21:31,90,10.19
2,0,1,1,hotel,0,14-09-2022,18:54:30,14-09-2022,19:54:29,14-09-2022 18:54,14-09-2022 19:54,60,6.78
3,0,1,1,hotel,0,29-09-2022,18:32:51,30-09-2022,00:16:42,29-09-2022 18:32,30-09-2022 00:16,344,37.65
4,0,1,1,hotel,0,25-09-2022,19:30:15,26-09-2022,00:30:14,25-09-2022 19:30,26-09-2022 00:30,300,33.81

(72856, 13)

<class 'pandas.DataFrame'>
RangeIndex: 72856 entries, 0 to 72855
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   UserID          72856 non-null  int64
 1   ChargerID       72856 non-null  int64
 2   ChargerCompany  72856 non-null  int64
 3   Location        72856 non-null  str
 4   ChargerType     72856 non-null  int64
 5   StartDay        72856 non-null  str
 6   StartTime       72856 non-null  str
 7   EndDay          72856 non-null  str
 8   EndTime         72856 non-null  str
 9   StartDatetime   72856 non-null  str
 10  EndDatetime     72856 non-null  str
 11  Duration        72856 non-null  int64
 12  Demand          72856 non-null  float64
dtypes: float64(1), int64(5), str(7)
memory usage: 7.2 MB

In [4]:
df.isnull().sum()

UserID            0
ChargerID         0
ChargerCompany    0
Location          0
ChargerType       0
StartDay          0
StartTime         0
EndDay            0
EndTime           0
StartDatetime     0
EndDatetime       0
Duration          0
Demand            0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(13)

In [6]:
df[df.duplicated()]

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
28857,329,214,1,public area,0,12-02-2022,07:22:40,12-02-2022,15:44:27,12-02-2022 07:22,12-02-2022 15:44,502,54.34
28859,329,214,1,public area,0,15-02-2022,19:29:42,15-02-2022,23:03:11,15-02-2022 19:29,15-02-2022 23:03,213,23.68
28862,329,214,1,public area,0,17-02-2022,18:53:55,18-02-2022,03:38:13,17-02-2022 18:53,18-02-2022 03:38,524,58.06
40670,461,371,1,apartment,0,22-02-2022,16:17:01,22-02-2022,21:38:44,22-02-2022 16:17,22-02-2022 21:38,322,37.74
51499,276,640,0,company,1,26-02-2022,09:23:02,26-02-2022,10:03:07,26-02-2022 09:23,26-02-2022 10:03,40,15.04
56653,1956,854,0,public area,1,15-02-2022,06:19:05,15-02-2022,07:36:38,15-02-2022 06:19,15-02-2022 07:36,78,49.07
57316,582,900,0,public parking lot,1,24-02-2022,09:49:03,24-02-2022,10:29:04,24-02-2022 09:49,24-02-2022 10:29,40,18.29
60212,228,1045,0,public area,1,26-02-2022,18:24:08,26-02-2022,18:39:59,26-02-2022 18:24,26-02-2022 18:39,16,10.54
61146,615,1094,0,hotel,0,05-02-2022,20:36:57,05-02-2022,22:40:37,05-02-2022 20:36,05-02-2022 22:40,124,13.93
64958,1146,1341,0,hotel,0,04-02-2022,18:13:23,05-02-2022,01:00:26,04-02-2022 18:13,05-02-2022 01:00,407,32.11
66121,156,1450,0,public parking lot,1,21-02-2022,12:03:16,21-02-2022,12:43:16,21-02-2022 12:03,21-02-2022 12:43,40,13.56
71101,1955,2086,0,public area,1,24-02-2022,16:37:14,24-02-2022,16:52:12,24-02-2022 16:37,24-02-2022 16:52,15,7.35
72780,1858,2605,0,apartment,0,27-02-2022,22:12:35,28-02-2022,04:29:06,27-02-2022 22:12,28-02-2022 04:29,377,22.60

In [7]:
df_c = df.drop_duplicates()
df_c.shape

(72843, 13)

In [8]:
df_c.describe(include='all')

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
count,72843.000000,72843.000000,72843.000000,72843,72843.000000,72843,72843,72843,72843,72843,72843,72843.000000,72843.000000
unique,NaN,NaN,NaN,14,NaN,366,43245,365,46710,65628,66745,NaN,NaN
top,NaN,NaN,NaN,public area,NaN,10-08-2022,18:28:39,28-07-2022,04:10:01,16-05-2022 15:10,22-09-2022 03:10,NaN,NaN
freq,NaN,NaN,NaN,14076,NaN,310,8,310,66,5,5,NaN,NaN
mean,338.084716,525.404143,0.627500,NaN,0.205195,NaN,NaN,NaN,NaN,NaN,NaN,151.183998,17.442667
std,553.916404,569.481406,0.483474,NaN,0.403847,NaN,NaN,NaN,NaN,NaN,NaN,146.420312,13.491446
min,0.000000,1.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,-29.000000,0.010000
25%,0.000000,107.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,40.000000,7.530000
50%,62.000000,301.000000,1.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,112.000000,14.100000
75%,407.000000,738.000000,1.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,202.000000,23.200000
max,2501.000000,2671.000000,1.000000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,1573.000000,97.000000

In [9]:
df_c['StartDatetime'] = pd.to_datetime(df_c['StartDatetime'])
df_c['EndDatetime'] = pd.to_datetime(df_c['EndDatetime'])
df_c = df_c.drop(columns=['StartDay','StartTime','EndDay','EndTime'])
df_c.dtypes

C:\Users\ssasi\AppData\Local\Temp\ipykernel_20220\1784156876.py:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_c['StartDatetime'] = pd.to_datetime(df_c['StartDatetime'])
C:\Users\ssasi\AppData\Local\Temp\ipykernel_20220\1784156876.py:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_c['EndDatetime'] = pd.to_datetime(df_c['EndDatetime'])

UserID                     int64
ChargerID                  int64
ChargerCompany             int64
Location                     str
ChargerType                int64
StartDatetime     datetime64[us]
EndDatetime       datetime64[us]
Duration                   int64
Demand                   float64
dtype: object

In [10]:
invalid = df_c[df_c['StartDatetime']>df_c['EndDatetime']]
invalid

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDatetime,EndDatetime,Duration,Demand
55422,1403,775,0,market,1,2022-02-15 15:04:00,2022-02-15 14:35:00,-29,11.68
55425,1403,775,0,market,1,2022-02-24 14:27:00,2022-02-24 14:18:00,-9,34.56
55427,1403,775,0,market,1,2022-01-17 14:47:00,2022-01-17 14:39:00,-8,17.77
55455,37,778,0,market,1,2022-04-29 18:58:00,2022-04-29 18:52:00,-6,31.90
55457,55,778,0,market,1,2022-05-07 16:24:00,2022-05-07 16:03:00,-21,13.39
55458,74,778,0,market,1,2022-04-29 15:48:00,2022-04-29 15:43:00,-6,19.36
55459,92,778,0,market,1,2022-03-27 15:17:00,2022-03-27 15:10:00,-7,20.99
55460,92,778,0,market,1,2022-02-05 18:52:00,2022-02-05 18:50:00,-2,31.59
55464,266,778,0,market,1,2022-05-08 12:02:00,2022-05-08 11:42:00,-20,3.28
55465,326,778,0,market,1,2022-01-09 14:29:00,2022-01-09 14:20:00,-9,31.68
55469,1768,778,0,market,1,2022-04-07 12:25:00,2022-04-07 12:12:00,-13,53.24
57800,55,922,0,market,1,2022-04-09 11:29:00,2022-04-09 11:23:00,-6,41.08
57802,1474,922,0,market,1,2022-05-05 17:48:00,2022-05-05 17:31:00,-16,51.99
57803,1766,922,0,market,1,2022-04-17 18:59:00,2022-04-17 18:54:00,-5,15.04
63503,1575,1229,0,market,1,2022-03-19 15:32:00,2022-03-19 15:24:00,-8,37.97
63504,1575,1229,0,market,1,2022-03-22 17:19:00,2022-03-22 16:55:00,-24,25.49
65029,140,1347,0,market,1,2022-03-30 13:20:00,2022-03-30 13:04:00,-16,23.10

In [11]:
invalid.shape[0]

17

In [24]:
df_c = df_c[df_c['StartDatetime']<df_c['EndDatetime']]
df_c.shape

(72296, 9)

In [13]:
df_c[['StartDatetime','EndDatetime']].describe()

                    StartDatetime                 EndDatetime
count                       72843                       72843
mean   2022-04-19 11:51:21.575717  2022-04-19 14:26:51.334788
min           2021-09-30 17:14:00         2021-10-01 00:07:00
25%           2022-01-25 21:39:30         2022-01-26 02:36:00
50%           2022-04-27 14:19:00         2022-04-27 15:39:00
75%           2022-07-17 09:58:30         2022-07-17 11:47:00
max           2022-09-30 23:11:00         2022-09-30 23:52:00

In [14]:
df_c['Duration'] = (df_c['EndDatetime'] - df_c['StartDatetime']).dt.total_seconds() / 60

In [15]:
df_c['Duration'].value_counts().get(0,0)

np.int64(530)

In [16]:
df_c['UserID'].value_counts()

UserID
0       31553
31        353
95        348
179       341
40        323
        ...
2405        1
2169        1
1918        1
2335        1
2155        1
Name: count, Length: 2337, dtype: int64

In [36]:
df_c[df_c['ChargerID']==0].value_counts()

Series([], Name: count, dtype: int64)

In [37]:
df_c['ChargerCompany'].value_counts()

ChargerCompany
1    45403
0    26893
Name: count, dtype: int64

In [38]:
df_c['Location'].value_counts()

Location
apartment             13972
public area           13963
resort                 8754
hotel                  8496
company                7528
public institution     6978
public parking lot     3367
market                 2970
restaurant             2215
camping                1620
sightseeing            1192
golf                   1026
accommodation           186
bus garage               29
Name: count, dtype: int64

In [39]:
df_c['ChargerType'].value_counts()

ChargerType
0    57540
1    14756
Name: count, dtype: int64

In [41]:
df_c.to_csv(r"D:\Sasi\GUVI HCL AI-ML\EV_Charging Project\data\cleaned\CleanedChargingRecords.csv",index=False)